name: medisync_hms
description: MediSync - Hospital Management System with Telematics Support

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.13.2
  flutter_svg: ^2.0.10+1
  fluentui_system_icons: ^1.1.236
  provider: ^6.1.2
  ionicons: ^0.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/

  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
